### ISSUE TITLE
Error occurred while enabling Psychics v2.0.0-SNAPSHOT (Is it up to date?)

### ISSUE THREAD

**Issue by kdh8219** [monun/psychics#102]
### Issue Duplicate

- [x] 이 버그에 대한 다른 Issue가 없는 것을 확인했습니다.

### 개발 OS

Windows 11 pro (22000.795)

### 개발 JDK

java version "1.8.0_341" Java(TM) SE Runtime Environment (build 1.8.0_341-b10) Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

### 개발 마인크래프트 버전

1.19

### 어떤 버그가 발생했나요?

[2762124](https://github.com/monun/psychics/commit/2762124164090a9a3d1554bf013facc64b635133) 를 내려받아서 paper jar로 빌드 한 후, psychics-core-2.0.0-SNAPSHOT.jar(Psychics.jar로 이름을 바꾸거나, 해당 파일을 사용해 보기도 하였으나 동일 하였습니다. )를 plugins 폴더에 넣은 feather client 의 paper 서버 실행시, 다음과 같은 오류가 나타납니다.
![image](https://user-images.githubusercontent.com/65698239/181597745-58eaefc1-cf0a-42ae-be2e-cef436e3c7ca.png)

### 어떻게 작동해야 하나요?

정상적으로 플러그인과 능력이 로드되기를 예상했습니다.

### 재현하기 위한 과정이 무엇인가요?

1. [2762124](https://github.com/monun/psychics/commit/2762124164090a9a3d1554bf013facc64b635133)를 내려받는다.
2. paper jar을 실행해 빌드한다.
3. 코어의 psychics-core-2.0.0-SNAPSHOT.jar를 plugins 폴더에 넣는다
4. 능력도 적당한걸로 하나 넣는다.
5. 실행한다.

### 소스코드가 무엇인가요?

[2762124](https://github.com/monun/psychics/commit/2762124164090a9a3d1554bf013facc64b635133)를 소스코드 변경 없이 빌드해서 사용했습니다.

**Comment by muqhc** [comment]
[psychics](https://github.com/monun/psychics)/[psychics-core](https://github.com/monun/psychics/tree/master/psychics-core)/[src](https://github.com/monun/psychics/tree/master/psychics-core/src)/[main](https://github.com/monun/psychics/tree/master/psychics-core/src/main)/[resources](https://github.com/monun/psychics/tree/master/psychics-core/src/main/resources)/[plugin.yml](https://github.com/monun/psychics/tree/master/psychics-core/src/main/resources/plugin.yml) 
```yaml
name: Psychics
main: io.github.monun.psychics.plugin.PsychicsPlugin
api-version: '1.17'
version: $version
author: Monun
libraries:
  - io.github.monun:tap:4.1.9
  - io.github.monun:invfx:3.0.1
  - io.github.monun:kommand:2.6.6
```

여기서
- io.github.monun:tap:4.1.9
- io.github.monun:kommand:2.6.6

위 두 라이브러리는 nms 기반으로 1.17버전 까지만 구현되어 있습니다.

1.19버전에서 사용하기 위해서는,
- io.github.monun:tap-core:4.6.0
- io.github.monun:kommand-core:2.12.0

으로 라이브러리를 최신버전으로 업데이트 해주셔야 합니다.

```yaml
name: Psychics
main: io.github.monun.psychics.plugin.PsychicsPlugin
api-version: '1.17'
version: $version
author: Monun
libraries:
  - io.github.monun:tap-core:4.6.0
  - io.github.monun:invfx:3.0.1
  - io.github.monun:kommand-core:2.12.0
```
