### ISSUE TITLE
뱀파이어 흡혈 무한 피복사 버그

### ISSUE THREAD

**Issue by myoun** [monun/psychics#55]
**Describe the bug (어떤 버그인가요?)**

뱀파이어의 흡혈 능력으로 아머스탠드를 때릴시 핏방울이 나옵니다.
이걸 이용해서 무한 피 복사가 가능합니다.
(적당한 속도로 때릴 시 아머스탠드는 부서지지 않음)

**To Reproduce (재현 과정)**
(동작을 재현하는 단계는 다음과 같습니다)
1. 아머스탠드를 설치합니다.
2. 아머스탠드를 적당한 속도로 계속 때려줍니다.
3. 핏방울이 계속 생성됩니다.

**Expected behavior (예상한 동작)**
핏방울이 나오지 않고 부셔집니다.

**Screenshots (스크린샷)**
(가능하면, 스크린샷을 올려서 이해하기 쉽게 해 주세요.)
![image](https://user-images.githubusercontent.com/76814120/133013153-b451855f-2c6f-4d82-9a40-63521126d243.png)

**Environment (개발 환경)**
- OS : Windows 11
- JDK version : Corretto-16.0.2.7.1 (build 16.0.2+7)
- Minecraft version : 1.17.1

**Source Code(소스 코드)**
```yml
abilities:
  vampire:
    ability: .vampire
    common:
      display-name: 흡혈
      type: PASSIVE
      interruptible: false
      supply-items: []
      description:
      - '{"italic":false,"color":"white","text":"적에게 피해를 입히면 주위에 핏방울이 생성됩니다."}'
      - '{"italic":false,"color":"white","text":"핏방울 근처로 이동하면 사라지며 체력을 회복합니다."}'
    vampire:
      heal-by-damage: 0.1
      orb-ticks-lived: 5400
      orb-pickup-delay: 10
      orb-velocity: 0.35
display-name: vampire
health-bonus: 0.0
health-regen-per-second: 0.0
mana: 0.0
mana-regen-per-second: 0.0
mana-color: BLUE
description:
- '{"italic":false,"color":"white","text":"설명"}'
```

**Additional context(추가 설명)**
힘 255걸고 아머스탠드 때리고 그거 핏방울 먹으면 체력이 엄청나게 많이 차네요
